### ISSUE TITLE
Issue under other locales

### ISSUE THREAD

**Issue by oderwat** [bakks/poptop#1]
I wanted to try it on my system and got `panic: strconv.ParseFloat: parsing "49,4": invalid syntax` which looks like there is some hard-coded conversation that expects English numbers.

**Comment by bakks** [comment]
Hey @oderwat - Yep I think you're correct, it's trying to parse the output of the `ps` command and expects periods rather than commas. I just pushed a fix and released as v0.1.6, you should be able to try it out by running `brew upgrade bakks/bakks/poptop` (assuming you installed via homebrew). Let me know if it works!

**Comment by oderwat** [comment]
That fixed it! Thank you for your work!
